@baseurl = http://localhost:3000

### Signup User
POST {{baseurl}}/api/user
Content-Type: application/json

{
  "name": "User4",
  "email": "user4@example.com"
}

# Response file: ./user.response.http
